apps = {'ag': ['ag-web-01.atl.primedia.com',
                    'ag-web-01.lax.primedia.com',
                    'ag-web-02.atl.primedia.com',
                    'ag-web-02.lax.primedia.com',
                    'ag-web-03.atl.primedia.com',
                    'ag-web-03.lax.primedia.com',
                    'ag-web-04.atl.primedia.com',
                    'ag-web-04.lax.primedia.com',
                    'ag-web-05.atl.primedia.com',
                    'ag-web-05.lax.primedia.com',
                    'ag-web-06.atl.primedia.com',
                    'ag-web-06.lax.primedia.com',
                    'ag-web-07.atl.primedia.com',
                    'ag-web-07.lax.primedia.com',
                    'ag-web-08.atl.primedia.com',
                    'ag-web-08.lax.primedia.com',
                    'ag-web-09.atl.primedia.com',
                    'ag-web-09.lax.primedia.com',
                    'ag-web-10.atl.primedia.com',
                    'ag-web-10.lax.primedia.com'],
            'rentals': ['rentals-web-01.atl.primedia.com',
                        'rentals-web-01.lax.primedia.com',
                        'rentals-web-02.atl.primedia.com',
                        'rentals-web-02.lax.primedia.com',
                        'rentals-web-03.atl.primedia.com',
                        'rentals-web-03.lax.primedia.com',
                        'rentals-web-04.atl.primedia.com',
                        'rentals-web-04.lax.primedia.com',
                        'rentals-web-05.atl.primedia.com',
                        'rentals-web-05.lax.primedia.com',
                        'rentals-web-06.atl.primedia.com',
                        'rentals-web-06.lax.primedia.com'],
            'mag': ['mag-web-01.atl.primedia.com',
                        'mag-web-01.lax.primedia.com',
                        'mag-web-02.atl.primedia.com',
                        'mag-web-02.lax.primedia.com',
                        'mag-web-03.atl.primedia.com',
                        'mag-web-03.lax.primedia.com',
                        'mag-web-04.atl.primedia.com',
                        'mag-web-04.lax.primedia.com',
                        'mag-web-05.atl.primedia.com',
                        'mag-web-05.lax.primedia.com'],
            'mnhg': ['mnhg-web-01.atl.primedia.com',
                        'mnhg-web-01.lax.primedia.com',
                        'mnhg-web-02.atl.primedia.com',
                        'mnhg-web-02.lax.primedia.com'],
            'agsites': ['agsites-web-01.atl.primedia.com',
                        'agsites-web-01.lax.primedia.com',
                        'agsites-web-02.atl.primedia.com',
                        'agsites-web-02.lax.primedia.com'],
            'myag': ['myag-web-01.atl.primedia.com',
                        'myag-web-02.atl.primedia.com'],
            'rnrui': ['rnrui-web-01.atl.primedia.com',
                        'rnrui-web-02.atl.primedia.com'],
                        }


site_mappings = {
    'ag': 'www.apartmentguide.com',
    'rentals': 'www.rentals.com',
    'mag': 'm.apartmentguide.com',
    'agsites': 'agsites.com',
    'mnhg': 'm.newhomeguide.com',
    'agsites': 'agsites.com',
    'myag': 'my.apartmentguide.com',
    'rnrui': 'rnrui'
}
